import React from "react";

const About = () => {
  return (
    <section className="mt-10">
      <div className="w-full h-full pl-20 pr-20 flex flex-col items-center">
        <div className="font-russo text-4xl mb-5">About Us</div>
        <div className="font-work text-sm w-1/2 text-center">
          Track Stack aims to build an all-inclusive audio NFT platform that
          focuses on granting artists full autonomy over their work, as well as
          allowing collectors to share in profits generated by the platform. Our
          platform will revolutionize the music NFT space through the use of
          segmented tracks, which we call ‘snippets’. The trading of these
          snippets will allow our users to turn a profit by listening to their
          favorite musicians and creators.
        </div>
        <div className="font-work font-black mt-5">One For All</div>
        <div className="font-bold mt-5 mb-5">Join Waitlist</div>
      </div>
    </section>
  );
};

export default About;
