import React from "react";

import Button from "./Button";

const About = () => {
  return (
    <section className="w-full px-16 h-fit flex flex-col items-center mt-10 space-y-6">
      <div className="font-russo text-4xl">About Us</div>
      <div className="font-work text-sm w-1/2 text-center">
        Track Stack aims to build an all-inclusive audio NFT platform that
        focuses on granting artists full autonomy over their work, as well as
        allowing collectors to share in profits generated by the platform. Our
        platform will revolutionize the music NFT space through the use of
        segmented tracks, which we call ‘snippets’. The trading of these
        snippets will allow our users to turn a profit by listening to their
        favorite musicians and creators.
      </div>
      <div className="font-work font-black">One For All</div>
      <Button text={"Join Waitlist"} styles={"font-bold"} />
    </section>
  );
};

export default About;
